module.exports = {
  apps: [
    {
      name: "swarm-api",
      script: "bun",
      args: "run start:http",
      cwd: __dirname,
    },
    {
      name: "swarm-ui",
      script: "pnpm",
      args: ["run", "dev", "--port", "5274"],
      cwd: `${__dirname}/ui`,
    },
    {
      name: "swarm-lead",
      script: "docker",
      args: [
        "run",
        "--rm",
        "--name",
        "swarm-lead",
        "--env-file",
        ".env.docker-lead",
        "-e",
        "AGENT_ROLE=lead",
        "-p",
        "3201:3000",
        "-v",
        "./logs:/logs",
        "-v",
        "./work/shared:/workspace/shared",
        "-v",
        "./work/lead:/workspace/personal",
        "agent-swarm-worker:latest",
      ],
      cwd: __dirname,
      autorestart: true,
      restart_delay: 5000,
    },
    {
      name: "swarm-worker",
      script: "docker",
      args: [
        "run",
        "--rm",
        "--name",
        "swarm-worker",
        "--env-file",
        ".env.docker",
        "-p",
        "3202:3000",
        "-v",
        "./logs:/logs",
        "-v",
        "./work/shared:/workspace/shared",
        "-v",
        "./work/worker-1:/workspace/personal",
        "agent-swarm-worker:latest",
      ],
      cwd: __dirname,
      autorestart: true,
      restart_delay: 5000,
    },
  ],
};
