/**
 * Generates API reference pages from the OpenAPI spec, grouped by tag.
 * Run: bun scripts/generate-docs.ts
 *
 * Reads ../openapi.json and creates:
 * - content/docs/api-reference/index.mdx (overview with version)
 * - content/docs/api-reference/<tag>.mdx (one per tag group)
 * - content/docs/api-reference/meta.json (auto-generated sidebar)
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const specPath = resolve(__dirname, "../../openapi.json");
const outputDir = resolve(__dirname, "../content/docs/api-reference");

const spec = JSON.parse(readFileSync(specPath, "utf-8"));

const version: string = spec.info?.version ?? "unknown";
const serverUrl: string =
  spec.servers?.[0]?.url ?? "http://localhost:3013";

// --- Group operations by tag ---

interface Operation {
  path: string;
  method: string;
  summary: string;
}

const tagGroups = new Map<string, Operation[]>();

for (const [path, methods] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(
    methods as Record<string, unknown>,
  )) {
    if (typeof op !== "object" || op === null) continue;
    const opObj = op as { tags?: string[]; summary?: string };
    const tags = opObj.tags?.length ? opObj.tags : ["Other"];
    for (const tag of tags) {
      if (!tagGroups.has(tag)) tagGroups.set(tag, []);
      tagGroups.get(tag)!.push({
        path,
        method,
        summary: opObj.summary ?? "",
      });
    }
  }
}

// Sort tags alphabetically, sort operations within each tag
const sortedTags = [...tagGroups.keys()].sort();
for (const tag of sortedTags) {
  tagGroups
    .get(tag)!
    .sort(
      (a, b) =>
        a.path.localeCompare(b.path) || a.method.localeCompare(b.method),
    );
}

// --- Slug helper ---

function slugify(tag: string): string {
  return tag
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// --- Clean output directory (remove old generated .mdx files) ---

mkdirSync(outputDir, { recursive: true });

if (existsSync(outputDir)) {
  for (const file of readdirSync(outputDir)) {
    if (file.endsWith(".mdx")) {
      rmSync(resolve(outputDir, file));
    }
  }
}

// --- Generate index page ---

const totalOps = [...tagGroups.values()].reduce(
  (sum, ops) => sum + ops.length,
  0,
);

const tagList = sortedTags
  .map((tag) => {
    const slug = slugify(tag);
    const count = tagGroups.get(tag)!.length;
    return `- [${tag}](/docs/api-reference/${slug}) — ${count} endpoint${count !== 1 ? "s" : ""}`;
  })
  .join("\n");

const indexMdx = `---
title: API Reference
description: REST API reference for Agent Swarm v${version}
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

## Agent Swarm API v${version}

Base URL: \`${serverUrl}\`

${totalOps} endpoints across ${sortedTags.length} categories.

### Categories

${tagList}
`;

writeFileSync(resolve(outputDir, "index.mdx"), indexMdx);

// --- Generate per-tag pages ---

for (const tag of sortedTags) {
  const slug = slugify(tag);
  const ops = tagGroups.get(tag)!;
  const opsJson = JSON.stringify(
    ops.map((o) => ({ path: o.path, method: o.method })),
  );

  const tagMdx = `---
title: "${tag}"
description: "${tag} API endpoints"
full: true
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

<APIPage document={"../openapi.json"} operations={${opsJson}} />
`;

  writeFileSync(resolve(outputDir, `${slug}.mdx`), tagMdx);
}

// --- Generate meta.json ---

const pages = [
  "index",
  ...sortedTags.map(slugify),
];

const metaJson = {
  title: `API Reference v${version}`,
  description: "REST API reference for Agent Swarm",
  root: true,
  pages,
};

writeFileSync(
  resolve(outputDir, "meta.json"),
  `${JSON.stringify(metaJson, null, 2)}\n`,
);

console.log(
  `Generated API reference: ${sortedTags.length} tag pages + index (${totalOps} operations, v${version})`,
);
